config/routes.rb
Angelhack2013Drip::Application.routes.draw do
  root :to => 'home#index'

  # auths
  match '/auth/twitter/callback' => 'sessions_twitter#create'
  match '/signout_twitter' => 'sessions_twitter#destroy'
  match '/signin_twitter' => 'sessions_twitter#new'
  match '/auth/facebook/callback' => 'sessions_facebook#create'
  match '/signout_facebook' => 'sessions_facebook#destroy'
  match '/signin_facebook' => 'sessions_facebook#new'

  resources :users
  get '/info', to: 'users#info', as: 'user_info'
  get '/donate', to: 'users#donate', as: 'donate'

  # stats
  get '/leaderboard', to: 'clinic#info', as: 'leaderboard'
  get '/map', to: 'clinic#map', as: 'map'
end

app/models/achievement.rb
class Achievement

  attr_reader :user

  def initialize(user)
    @user = user
  end

  def pints_count
    user.donations.count
  end

  def people_saved
    pints_count * 3
  end

  def message
    if pints_count == 1
      "two teacup pigs"
    elsif pints_count == 2
      "the Holy Grail (est.)"
    elsif pints_count == 5
      "a heart surgery"
    elsif pints_count == 9
      "the Stanley Cup"
    elsif pints_count == 13
      "a case of beer"
    elsif pints_count == 50
      "a car accident victim"
    elsif pints_count == 54
      "the Queen of England's corgis"
    end
  end

  def in_app_message
    "Thanks for giving blood: you've donated as much as #{message}."
  end

  def social_message
    "I gave blood today and have donated a total volume of blood equivalent to #{message} - using drip"
  end

  def celebrate
    user.broadcast(social_message)
  end

end

app/models/auth.rb
class Auth < ActiveRecord::Base
  has_one :user_auth
  has_one :user, through: :user_auth
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  has_many :clinic_schedules
  has_many :donations
  accepts_nested_attributes_for :clinic_schedules

  reverse_geocoded_by :x_coord, :y_coord

  def self.city_donation_stats
    city_stats = Hash.new(0)
    cities = Clinic.all.group_by(&:city)
    cities.keys.each do |city|
      cities[city].each do |clinic|
        city_stats[city] += clinic.donations.count * 0.473176473
      end
    end
    city_stats.sort_by{ |k,v| v }.reverse
  end

  def self.clinic_donation_stats
    clinic_stats = Hash.new(0)
    Clinic.all.each do |clinic|
      clinic_stats[clinic.address] = clinic.donations.count * 0.473176473
    end
    clinic_stats.sort_by{ |k,v| v }.reverse
  end

  def currently_open?
    # data for clinics sucks.. need to normalize begin & close times
    if open_clinic = self.clinic_schedules.where(date: Date.today)
      return true
    end
    return false
  end
end

app/models/clinic_schedule.rb
class ClinicSchedule < ActiveRecord::Base
  belongs_to :clinic
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :clinic
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_auths
  has_many :auths, through: :user_auths
  has_many :donations

  def self.create_with_omniauth_facebook(auth_params)
    user = User.new
    if auth_params['info']
      user.name = auth_params['info']['name'] || ""
      user.email = auth_params['info']['email'] || ""
    end
    user.save
    user.auths.create(
      provider: auth_params['provider'],
      uid: auth_params['uid'],
      token: auth_params['credentials']['token'])
  end

  def self.create_with_omniauth_twitter(auth_params)
    user = User.new
    if auth_params['info']
      user.name = auth_params['info']['name'] || ""
    end
    user.save
    user.auths.create(
      provider: auth_params['provider'],
      uid: auth_params['uid'],
      token: auth_params['credentials']['token'],
      secret: auth_params['credentials']['secret']
    )
  end

  def broadcast(msg)
    if twitter_auth
      tweeter = Twitter::Client.new(
        oauth_token: twitter_auth.token,
        oauth_token_secret: twitter_auth.secret
        )
      tweeter.update(msg)
    end
    if facebook_auth
      fb = Koala::Facebook::API.new(facebook_auth.token)
      fb.put_wall_post(msg)
    end
  end

  def can_donate?
    days_until_can_donate < 1
  end

  def days_until_can_donate
    last = self.donations.last
    if last
      return 60 - (Date.today - last.date).to_i
    else
      return 0
    end
  end

  private

  def twitter_auth
    auths.where(provider: 'twitter').first
  end

  def facebook_auth
    auths.where(provider: 'facebook').first
  end

end

app/models/user_auth.rb
class UserAuth < ActiveRecord::Base
  belongs_to :user
  belongs_to :auth
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= (User.find(session[:user_id]) if session[:user_id])
  end

  helper_method :current_user

end

app/controllers/clinic_controller.rb
class ClinicController < ApplicationController

  def info
    @clinic_stats = Clinic.clinic_donation_stats
    @city_stats = Clinic.city_donation_stats
    @country_stats = []
  end

  def city_stats
    @current_stats = Clinic.city_donation_stats
    render json: @current_stats.to_json
  end

  def clinic_stats
    @current_stats = Clinic.clinic_donation_stats
    render json: @current_stats.to_json
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_facebook_controller.rb
class SessionsFacebookController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth_params = request.env["omniauth.auth"]
    auth = Auth.where(provider: auth_params['provider'], uid: auth_params['uid']).first
    if auth
      user = auth.user
    else
      user = User.create_with_omniauth_facebook(auth_params)
    end
    session[:user_id] = user.id
    session[:provider] = 'facebook'
    redirect_to user_info_path, :notice => "Signed in!"
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Signed out!'
  end
end

app/controllers/sessions_twitter_controller.rb
class SessionsTwitterController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end

  def create
    auth_params = request.env["omniauth.auth"]
    auth = Auth.where(provider: auth_params['provider'], uid: auth_params['uid']).first
    if auth
      user = auth.user
    else
      user = User.create_with_omniauth_twitter(auth_params)
    end
    session[:user_id] = user.id
    session[:provider] = 'twitter'
    redirect_to user_info_path, :notice => "Signed in!"
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Signed out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def info
    unless current_user
      redirect_to(:controller => 'home', :action => 'index') and return
    end
    @achievement = Achievement.new(current_user)
  end

  def update
    if current_user
      current_user.update_attributes(params[:user])
    end
    redirect_to user_info_path
  end

  def donate
    if current_user.can_donate?
      fakey = Clinic.new(x_coord: params[:latitude], y_coord: params[:longitude])
      nearest_clinic = fakey.nearbys(0.3, order: 'distance').first
      Donation.create(user: current_user, clinic: nearest_clinic, date: Date.today) if nearest_clinic.currently_open?
      @achievement = Achievement.new(current_user)
      render :info, :notice => @achievement.in_app_message
    else
      render :info,  :notice => "You can't donate now"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clinic/_stat_line.html.haml
- stats.each_index do |i|
  .stat_line
    .index= i+1
    .details= stats[i][0]
    .donations.last_stat= "#{stats[i][1].to_i} L"

app/views/clinic/info.html.haml
#nav_bar
  = image_tag('title_leaderboard.png')
#stat_select
  #clinic.stat_icon
    = image_tag('icon_clinic.png')
  #city.stat_icon
    = image_tag('icon_city.png')
  #country.stat_icon
    = image_tag('icon_country.png')
#stat_divide
#clinic_stats.stat_set
  = render 'clinic/stat_line', stats: @clinic_stats
#city_stats.stat_set
  = render 'clinic/stat_line', stats: @city_stats
#country_stats.stat_set
  = render 'clinic/stat_line', stats: @country_stats

app/views/clinic/map.html.haml
#nav_bar
  = image_tag('title_donate.png')
#map
#map_divide
#map_below_the_fold

app/views/home/index.html.haml
= image_tag('logo_drip.png', id: 'logo')

#sign_up
  = image_tag('title_catch_phrase.png')
  = image_tag('button_sign_up.png')

  #social_login
    = link_to image_tag('social_facebook.png'), signin_facebook_path
    = link_to image_tag('social_twitter.png'), signin_twitter_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Angelhack2013Drip</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "home" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/clinic.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drip - Leaderboard</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "clinic" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "clinic" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Angelhack2013Drip</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "home" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/info.html.haml
#user_info

  %h1
    Welcome
    - if current_user.name
      = current_user.name
    - if current_user.blood_type
      = "[#{current_user.blood_type}]"

  - unless current_user.email
    %p
      = form_for current_user, url_for: {action: 'update'} do |user_form|
        = user_form.label :email
        = user_form.text_field :email
        = user_form.submit 'Update'
  - unless current_user.blood_type
    %p
      = form_for current_user, url_for: {action: 'update'} do |user_form|
        = user_form.label :blood_type
        = user_form.select :blood_type, options_for_select(['O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-'])
        = user_form.submit 'Update'

  - if current_user.can_donate?
    = link_to 'DONATE', donate_path(longitude: 43.6475898, latitude: -79.3849767)
  - else
    %p
      = "You can donate again in #{pluralize(current_user.days_until_can_donate, "day")}"

  - if @achievement.pints_count > 0
    %p
      = "Donated: #{pluralize(@achievement.pints_count, "pint")}"
      %br
      = "Saved: #{@achievement.people_saved} lives"

  - if !@achievement.message.blank?
    %p
      = @achievement.in_app_message

  - if session[:provider] == 'facebook'
    = link_to 'SIGN OUT', signout_facebook_path
  - if session[:provider] == 'twitter'
    = link_to 'SIGN OUT', signout_twitter_path